name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH key and agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

    - name: Deploy to VM via SSH
      run: |
        ssh -o StrictHostKeyChecking=no dvt_mr_zkn@130.211.73.32 << 'EOF'
          cd ~/ml_pipeline_gcp
          git pull origin main
          # Add your deployment steps here, e.g.:
          # systemctl restart your-flask-app
        EOF

