name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to VM via SSH
      run: |
        echo "$GCP_SSH_PRIVATE_KEY" > key.pem
        chmod 600 key.pem
        ssh -i key.pem -o StrictHostKeyChecking=no dvt_mr_zkn@130.211.73.32 << 'EOF'
          cd ~/ml_pipeline_gcp
          git pull origin main
          pkill -f "python3 app/main.py" || true
          nohup python3 app/main.py > flask.log 2>&1 &
        EOF
      env:
        GCP_SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

